### ISSUE TITLE
mTLS with Ingress Controller Failing

### ISSUE THREAD

**Issue by urton** [openshift/cluster-ingress-operator#1195]
I don't know if this is the right place to bring this up, but I've run across this exact [issue](https://access.redhat.com/solutions/7106361).

I created this IngressController:
```yaml
---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: apps-mtls
  namespace: openshift-ingress-operator
spec:
  clientTLS:
    clientCA:
      name: my-ca
    clientCertificatePolicy: Required
    allowedSubjectPatterns:
    - "^/CN=client.my.domain/*"
  domain: my.domain
  endpointPublishingStrategy:
    loadBalancer:
      dnsManagementPolicy: Managed
      providerParameters:
        aws:
          type: NLB
        type: AWS
      scope: Internal
    type: LoadBalancerService
```
After initial deployment, we got the `tlsv1 alert unknown ca, errno 0` error regardless if the client cert was in the `allowedSubjectPatterns` or not. We noticed, in the router pods, that the CRL for our CA could not be downloaded. We adjusted our cluster proxy settings to remediate that, but we still had the error after remediation. According to the solutions link above, a client cert with a CRL distribution point is "invalid". Is this an HA Proxy issue or something can be alleviated via the ingress operator? I have never heard of a CRLDP invalidating a ssl cert that has type client auth. We use these same certs, for mTLS, with Kafka (via Strimzi), and AWS ALBs.

Any help and/or guidance is much appreciated. We were trying to keep our machine-to-machine mTLS solution "turnkey" in our ROSA cluster without installing any other operators (e.g. AWS LB Controller or Istio).
