### ISSUE TITLE
[RFE] Be able to specify topologyKey for router deployment

### ISSUE THREAD

**Issue by ghurel-rh** [openshift/cluster-ingress-operator#348]
Router deployment created by the operator are using the topology key "kubernetes.io/hostname" in its podAntiAffinity rule. 

It would be great if we can override this key, e.g. by "topology.kubernetes.io/zone" so that router pods can  be spread across different zones instead of different hosts.

**Comment by Miciah** [comment]
The scheduler spreads pods across zones by default (see [the documentation for `topology.kubernetes.io/zone`](https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#topologykubernetesiozone)), which provides equivalent functionality to a soft anti-affinity rule keyed by zone.  Using a hard anti-affinity rule keyed by zone would limit the number of replicas to the number of zones.

**Comment by ghurel-rh** [comment]
Hello @Miciah thank for your reply.

What you're saying is clear, however during my tests I could notice the scheduler prioritizes scheduling router pods across hosts and not across zones.

I believe this is due to the anti-affinity rule in the router deployment:
```
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: ingresscontroller.operator.openshift.io/deployment-ingresscontroller
                operator: In
                values:
                - default
            topologyKey: kubernetes.io/hostname
```
