### ISSUE TITLE
Switching from AWS CLB to NLB for router-default

### ISSUE THREAD

**Issue by htkmts** [openshift/cluster-ingress-operator#479]
Hi.
I am not sure if this is the right place to ask this question, but I really need help.

I installed OCP 4.5 private cluster on AWS.
Upon installation, I used AWS CloudFormation to create load balancers and 2 LBs were created.
 - 1 NLB for api calls to master nodes
 - 1 CLB for the routers on worker nodes

My client need static IP address for LBs and because AWS CLBs do not support static IPs,
I need to switch the CLB to a new NLB.

Does anyone have any ideas on how to achieve this?

Thanks.

**Comment by kim0** [comment]
I am not an openshift developer, but I had the same need and after working with support I achieved it using
```
#! To apply this special file use:
#! oc replace --force -f - --wait --save-config
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  replicas: 3
  defaultCertificate:
    name: router-certs
  endpointPublishingStrategy:
    loadBalancer:
      scope: Internal
      providerParameters:
        type: AWS
        aws:
          type: NLB
    type: LoadBalancerService
```
