### ISSUE TITLE
Feature Request: Make router log level configurable via ingress controller

### ISSUE THREAD

**Issue by halfcrazy** [openshift/cluster-ingress-operator#909]
We can enable and configure the log format in IngressController cr, but there is no way to configure the log level.
I found a default log level in the code, but there is no way to configure it. https://github.com/openshift/cluster-ingress-operator/blob/a29464eda9614ac3d70c185b572f4839195e7306/pkg/operator/controller/ingress/deployment.go#L50

And in nginx/haproxy conf
```
images/router/nginx/conf/nginx-config.template
10:{{ $logLevel := firstMatch "info|notice|warn|error|crit|alert|emerg" (env "ROUTER_LOG_LEVEL") "warn" }}

images/router/haproxy/conf/haproxy-config.template
61:  log {{ . }} len {{ env "ROUTER_LOG_MAX_LENGTH" "1024" }} {{ env "ROUTER_LOG_FACILITY" "local1" }} {{ env "ROUTER_LOG_LEVEL" "warning" }}
```

I proposal we can add a log-level field in IngressController cr.
```
  logging:
    access:
      destination:
        type: Container
      logEmptyRequests: Log
      logLevel: error # Add a new field
```

https://docs.openshift.com/container-platform/4.12/networking/ingress-operator.html
